apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitor-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: visitor
  template:
    metadata:
      labels:
        app: visitor
    spec:
      containers:
      - name: visitor
        image: <IMAGE>
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: host
